version: "3.9"

services:
  kong:
    image: kong:3.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - connect-career-be
      - ai-service

  connect-career-be:
    image: connect-career-be:latest
    ports:
      - "8080:8080"

  ai-service:
    image: ai-service:latest
    ports:
      - "8000:8000"
