version: "3.9"

services:
  kong:
    ports:
      - "80:8000"
      - "443:8443"
    environment:
      KONG_LOG_LEVEL: warn

  connect-career-be:
    environment:
      NODE_ENV: production

  ai-service:
    environment:
      NODE_ENV: production
