apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: connect-career
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: connect-career-be
        url: http://connect-career-be-service.connect-career.svc.cluster.local:80
        routes:
          - name: connect